In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-1.28673451,  0.68001713,  1.39994077, -2.24461256, -0.56316711,
       -0.11097254, -0.42307509, -0.69105773, -0.47356613,  0.84694625])

In [7]:
B = np.random.randn(10)
B

array([-2.14439124, -1.32320027, -0.93788798,  2.01146101,  0.69075616,
       -1.59701217, -0.24565051, -0.39493423,  0.92080976,  1.1109119 ])

In [8]:
# Binary Functions

np.add(A,B)

array([-3.43112575, -0.64318314,  0.46205279, -0.23315155,  0.12758905,
       -1.70798471, -0.6687256 , -1.08599197,  0.44724363,  1.95785815])

In [9]:
np.maximum(A,B)

array([-1.28673451,  0.68001713,  1.39994077,  2.01146101,  0.69075616,
       -0.11097254, -0.24565051, -0.39493423,  0.92080976,  1.1109119 ])